name: Deploy to VPS

on:
  push:
    branches:
      - main  
  pull_request:
    types:
      - closed
    branches:
      - main  

jobs:
  deploy:
    if: github.event.pull_request.merged == true || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build Next.js app
        run: npm run build

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
          
          # Copier les fichiers du projet (y compris .next)
          rsync -avz --exclude '.git' --exclude 'node_modules' ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ secrets.DEPLOY_PATH }}
          
          # Exécuter les commandes sur le serveur
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd ${{ secrets.DEPLOY_PATH }}
            npm install --production
            npm run build
            pm2 restart next-app || pm2 start npm --name "lodgic-dev" -- start
          EOF
